import { Router, Request, Response } from 'express';
import fs from 'fs';
import path from 'path';

const router = Router();
// __dirname when this file runs is server/src/routes
// So: __dirname/../../.. = server/src/routes/../../.. = root/
const repoRoot = path.resolve(__dirname, '..', '..', '..');
const backupDir = path.join(repoRoot, 'backups');

console.log('[backup] init: repoRoot =', repoRoot);
console.log('[backup] init: backupDir =', backupDir);

function ensureBackupDir() {
  try {
    if (!fs.existsSync(backupDir)) {
      console.log('[backup] creating backupDir:', backupDir);
      fs.mkdirSync(backupDir, { recursive: true });
      console.log('[backup] backupDir created successfully');
    }
  } catch (err) {
    console.error('[backup] failed to create backupDir:', backupDir, err);
    throw err;
  }
}

function safeReadJson(filePath: string) {
  try {
    if (!fs.existsSync(filePath)) return null;
    const raw = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    console.warn('[backup] failed to read sample file', filePath, err);
    return null;
  }
}

router.post('/', async (req: Request, res: Response) => {
  const { location } = req.body as { location?: 'local' | 'cloud' | 'both' };
  const loc = location || 'local';
  if (!['local', 'cloud', 'both'].includes(loc)) {
    return res.status(400).json({ ok: false, error: 'invalid location' });
  }

  try {
    console.log('[backup] start request', { loc });
    console.log('[backup] repoRoot resolved to:', repoRoot);
    console.log('[backup] backupDir resolved to:', backupDir);
    ensureBackupDir();

    const timestamp = new Date();
    const stamp = timestamp.toISOString().replace(/[^0-9]/g, '').slice(0, 14); // YYYYMMDDhhmmss
    const fileName = `backup-${stamp}-${loc}.json`;
    const filePath = path.join(backupDir, fileName);

    console.log('[backup] writing to:', filePath);

    const users = safeReadJson(path.join(repoRoot, 'server', 'data', 'users.json'));
    const sessions = safeReadJson(path.join(repoRoot, 'server', 'data', 'sessions.json'));

    const payload = {
      createdAt: timestamp.toISOString(),
      location: loc,
      note: 'Local demo backup generated by admin Run Now.',
      includes: {
        users: Array.isArray(users) ? users.length : (users?.users?.length ?? 0),
        sessions: Array.isArray(sessions) ? sessions.length : 0,
      },
      data: {
        users,
        sessions,
      },
    };

    const json = JSON.stringify(payload, null, 2);
    console.log('[backup] about to write', Buffer.byteLength(json, 'utf8'), 'bytes to:', filePath);
    fs.writeFileSync(filePath, json, 'utf8');
    console.log('[backup] writeFileSync completed');

    // Verify the file was actually written before claiming success
    const exists = fs.existsSync(filePath);
    const stat = exists ? fs.statSync(filePath) : null;
    console.log('[backup] file existence check:', { exists, filePath, statSize: stat?.size });
    
    if (!exists) {
      throw new Error(`File was not written or not found after write: ${filePath}`);
    }

    const sizeBytes = Buffer.byteLength(json, 'utf8');
    console.log('[backup] saved', { filePath, sizeBytes, statSize: stat?.size, fileExists: exists });

    return res.json({
      ok: true,
      fileName,
      filePath,
      sizeBytes,
      detail: `Saved backup to ${loc}: ${filePath} (${(sizeBytes / (1024 * 1024)).toFixed(2)} MB)`,
    });
  } catch (err) {
    console.error('[backup] failed to write backup', err);
    return res.status(500).json({ ok: false, error: 'Failed to write backup file', detail: String((err as Error)?.message || err) });
  }
});

export default router;
