import { Router, Request, Response } from 'express';
import fs from 'fs';
import path from 'path';

const router = Router();
// Anchor backups under the server folder (works in dev or dist)
const serverRoot = path.resolve(__dirname, '..', '..');
const backupDir = path.join(serverRoot, 'backups');

function ensureBackupDir() {
  if (!fs.existsSync(backupDir)) fs.mkdirSync(backupDir, { recursive: true });
}

function safeReadJson(filePath: string) {
  try {
    if (!fs.existsSync(filePath)) return null;
    const raw = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    console.warn('[backup] failed to read sample file', filePath, err);
    return null;
  }
}

router.post('/', async (req: Request, res: Response) => {
  const { location } = req.body as { location?: 'local' | 'cloud' | 'both' };
  const loc = location || 'local';
  if (!['local', 'cloud', 'both'].includes(loc)) {
    return res.status(400).json({ ok: false, error: 'invalid location' });
  }

  try {
    console.log('[backup] start request', { loc });
    ensureBackupDir();

    const timestamp = new Date();
    const stamp = timestamp.toISOString().replace(/[^0-9]/g, '').slice(0, 14); // YYYYMMDDhhmmss
    const fileName = `backup-${stamp}-${loc}.json`;
    const filePath = path.join(backupDir, fileName);

    const users = safeReadJson(path.join(serverRoot, 'data', 'users.json'));
    const sessions = safeReadJson(path.join(serverRoot, 'data', 'sessions.json'));

    const payload = {
      createdAt: timestamp.toISOString(),
      location: loc,
      note: 'Local demo backup generated by admin Run Now.',
      includes: {
        users: Array.isArray(users) ? users.length : (users?.users?.length ?? 0),
        sessions: Array.isArray(sessions) ? sessions.length : 0,
      },
      data: {
        users,
        sessions,
      },
    };

    const json = JSON.stringify(payload, null, 2);
    fs.writeFileSync(filePath, json, 'utf8');

    const sizeBytes = Buffer.byteLength(json, 'utf8');
    console.log('[backup] saved', { filePath, sizeBytes });

    return res.json({
      ok: true,
      fileName,
      filePath,
      sizeBytes,
      detail: `Saved backup to ${loc}: ${filePath} (${(sizeBytes / (1024 * 1024)).toFixed(2)} MB)`,
    });
  } catch (err) {
    console.error('[backup] failed to write backup', err);
    return res.status(500).json({ ok: false, error: 'Failed to write backup file', detail: String((err as Error)?.message || err) });
  }
});

export default router;
